[package]
name = "arq_plugins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.3"
tracing = "0.1.36"
rocket = "0.5.0-rc.2"
anyhow = "1.0.62"
